learner:
  type: baseline # multitask learning
  lr: 0.00001 # learning rate
  multitask: true  # whether the data is shown in a multitask fashion
  replay_rate: 0 # replay rate from memory

training:
  epochs: 1