wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    framework: huggingface
    huggingface_version: 3.0.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.7.6
      5: 0.10.14
      6: 3.0.2
      8:
      - 1
