#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:05:00
#SBATCH --mem=20G
#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:1
#SBATCH --output=./slurm_logs/R-%x.%j.out

#Loading modules
module purge
module load 2020
module load Python/3.8.2-GCCcore-9.3.0

# activate virtual environment
. venv/bin/activate

python train_text_cls.py learner=replay testing.n_samples=10 name=test  task_order=[agnews,yelp,evaluation,amazon,evaluation,yahoo,evaluation,dbpedia]  learner.samples_per_task=[10,10,5,10,5,10,5,10]  testing.eval_dataset=agnews seed=44 \
                            testing.average_accuracy=false testing.few_shot_validation_size=10